version: '3.3'

services:

  httpd:
    build:
      context: .
      dockerfile: httpd.Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./drupal:/var/www/drupal
    depends_on:
      - db
      - phpfpm

  phpfpm:
    build:
      context: .
      dockerfile: phpfpm.Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - ./drupal:/var/www/drupal
    depends_on:
      - db

  drush:
    build:
      context: .
      dockerfile: drush.Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - ./drupal:/var/www/drupal
      - ./etc/php/drush.php.ini:/usr/local/etc/php/conf.d/drush.php.ini
    depends_on:
      - db

  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: drupal
    depends_on:
      - db
    links:
      - db

  db:
    image: mariadb:latest
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal

volumes:
  mysqldata: